-- ============================================================
-- Deny 事件追踪 + 风险评分 数据库表
-- 在 ECS 上执行: sudo docker run --rm --network host -e PGPASSWORD='<密码>' postgres:16-alpine psql -h 127.0.0.1 -U postgres -d bdpan -f /path/to/deny-tables.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS bdpan_deny_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deny_source TEXT NOT NULL,
  deny_reason TEXT NOT NULL,
  ip TEXT NOT NULL,
  device_code TEXT,
  device_code_hash TEXT,
  user_agent TEXT,
  request_path TEXT,
  username TEXT,
  risk_score_added INTEGER NOT NULL DEFAULT 0,
  ip_risk_at_time REAL,
  dc_risk_at_time REAL,
  geo_country TEXT,
  geo_city TEXT,
  geo_region TEXT
);

CREATE TABLE IF NOT EXISTS bdpan_risk_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_value TEXT NOT NULL,
  current_score REAL NOT NULL DEFAULT 0,
  total_events INTEGER NOT NULL DEFAULT 0,
  last_offense_at TIMESTAMPTZ,
  last_offense_reason TEXT,
  is_banned BOOLEAN NOT NULL DEFAULT false,
  banned_at TIMESTAMPTZ,
  ban_expiry TIMESTAMPTZ,
  ban_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_risk_scores_entity ON bdpan_risk_scores(entity_type, entity_value);
CREATE INDEX IF NOT EXISTS idx_risk_scores_score ON bdpan_risk_scores(current_score DESC);
CREATE INDEX IF NOT EXISTS idx_deny_events_ip ON bdpan_deny_events(ip, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deny_events_dc ON bdpan_deny_events(device_code_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deny_events_dedup ON bdpan_deny_events(ip, request_path, created_at DESC);

-- 验证
SELECT 'bdpan_deny_events' AS tbl, count(*) FROM bdpan_deny_events
UNION ALL SELECT 'bdpan_risk_scores', count(*) FROM bdpan_risk_scores;
